name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './family-app/package-lock.json'

      - name: Install dependencies
        run: cd family-app && npm ci

      - name: Build and Export
        run: |
          cd family-app
          npm run build
          touch out/.nojekyll
          echo "eitan987.github.io" > out/CNAME
          echo '<!DOCTYPE html><html><head><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=/family.com/"></head><body>מפנה לדף הראשי...</body></html>' > out/404.html
          echo "/* /index.html 200" > out/_redirects
          echo "include: ['.nojekyll']" > out/_config.yml
          echo "baseurl: /family.com" >> out/_config.yml
          echo "permalink: pretty" >> out/_config.yml
        env:
          NODE_ENV: production
          NEXT_PUBLIC_BASE_PATH: /family.com

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch the action should deploy to
          folder: family-app/out  # The folder that the build-storybook script generates files
          clean: true  # Automatically remove deleted files from the deploy branch 